name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - openai
  - datasets
  - matplotlib
  - seaborn
  - pandas
  - tiktoken
  - ipython
  - jupyter
  - python-dotenv
  - pip
  - chromadb
  - fsspec=2023.9.2
